# Predicting Loan Default using Lending Club Dataset

**Part 1: Data Preparation, Exploration and Cleaning**

Load library and dataset

```{R}
pacman::p_load(dplyr, tidyverse, ggplot2, lubridate, reshape2, stringr, car, caret, ggpubr, dlookr, inspectdf)
setwd("C:/Users/Alvin/Documents/R Work Directory")
loans_all = read.csv("loans.csv", as.is = TRUE)
```

**Data exploration**  

Check if all rows are filled  
Show percentage missing entries for each variable  
Remove data with missing values since instances of NA is not significant (<5%)

```{R}
summary(loans_all)
colMeans(is.na(loans_all))*100
loans = loans_all[complete.cases(loans_all),]
glimpse(loans)
summary(loans)
nrow(loans)/nrow(loans_all)
```

99.8% of original entries are retained

Change dependent variable "target loan status" to factor

```{R}
loans$targetloanstatus <- as.factor(loans$targetloanstatus)
```

Exploratory Data Analysis 

Show current loan default status  
"Target loan status" =  1 means defaulted on loan

```{R}
loans %>%
  group_by(targetloanstatus)%>%
  summarise(per = n()/nrow(loans))%>%
  ggplot(aes(x=targetloanstatus, y=per, fill = targetloanstatus)) + 
  geom_bar(stat='identity') +
  geom_text(aes(label = round(per, 2)), vjust = 2) + labs(fill = "Loan Status", title = "Summary of Current Loan Status", x = "Loan Status", y = "Percentage")
```

15% of borrowers defaulted on loan

Plot percentage defaulted by grade

```{R}
p1 = loans %>%
  group_by(grade) %>%
  count(targetloanstatus) %>%
  mutate(percentage = n/sum(n)) %>%
  ggplot(aes(x = grade, y = percentage)) +
  geom_col(aes(fill = targetloanstatus)) + 
  labs(title = "percentage of defaulters") + ylab("default %")
```

Plot loan status by term of loan

```{R}
loans %>%
  group_by(term, targetloanstatus) %>%
  summarise(count_level = n(), percentage = n()/nrow(loans)) %>%
  ggplot(aes(x = term, y = percentage, fill = targetloanstatus)) +
  geom_bar(position = 'fill', stat = 'identity') +
  labs(title="Current Loan Status by Term", x = "Term", y = "Percentage", fill = "Loan Status") 
```

Higher chance of default for long term (60 months) loan

Plot loan status by grade and loan amount

```{R}
loans %>%
  ggplot(aes(grade, loanamnt)) +
  geom_boxplot(fill = "white", colour = "darkblue", 
               outlier.colour = "red", outlier.shape = 1) +
  scale_y_continuous() +
  facet_wrap(~ targetloanstatus) +
  labs(title="Loan Amount by Grade", x = "Grade", y = "Loan Amount")
```

Typically higher loan amount at lower grade  
Outliers are common for grades A - D  
The loan amount spread (IQR) is higher for lower grade loans

Plot loan status against grade 

```{R}
loans %>%
  group_by(grade, targetloanstatus) %>%
  summarise(count_level = n(), percentage = n()/nrow(loans)) %>%
  ggplot(aes(x = grade, y = percentage, fill = targetloanstatus)) +
  geom_bar(position = 'fill', stat = 'identity') +
  labs(title="Current Loan Status by Grade", x = "Grade", y = "Percentage", fill = "Loan Status") 
```

Plot revolving balance and target loan status

```{R}
loans %>%
  ggplot(aes(x = targetloanstatus)) +
  geom_boxplot(aes(y=revolbal), outlier.shape = NA) + facet_grid(~grade) + 
  scale_y_continuous(limits = c(0,20000))
```

Non-visual summaries

```{R}
loans %>%
  group_by(targetloanstatus) %>%
  summarise(ratio = n()/nrow(loans), count = n())

loans %>%
  group_by(targetloanstatus) %>%
  count(creditpolicy) %>%
  mutate(perc = n/sum(n))
```

**Data cleaning** 

Clean emplength and term lines

```{R}
table(loans$term, useNA = "always")
loans$term %>%
  str_extract("\\d{1,2}") -> loans$term

table(loans$emplength, useNA = "always")
loans$emplength %>%
  str_replace("< 1", "1") %>%
  str_replace("n/a", "0") %>%
  str_extract("\\d{1,2}") -> loans$emplength
loans[,c("term","emplength")] = 
  lapply(loans[,c("term","emplength")], as.integer)
table(loans$emplength, useNA = "always")
```

Convert grade to numeric class

```{R}
loans = loans %>%
  mutate(recodegrade = (case_when(grade == "A" ~ 1,
                                  grade == "B" ~ 2,
                                  grade == "C" ~ 3,
                                  grade == "D" ~ 4,
                                  grade == "E" ~ 5,
                                  grade == "F" ~ 6,
                                  grade == "G" ~ 7)))
```

Create 2 new variables for emp10years and delinq2years

```{R}
loans = loans %>%
  mutate(delin2years = factor(case_when(delinq2yrs > 0 ~ "Y",
                                        delinq2yrs == 0 ~ "N")),
         homeowner = factor(ifelse(homeownership == "MORTGAGE"|homeownership == "OWN",
                                   "Y", "N")))

table(loans$delin2years, loans$delinq2yrs)
table(loans$homeowner, loans$homeownership)
```

Apply log transformation to annualinc and revolbal

```{R}
loans = loans %>%
  mutate(logannualinc = log(1+annualinc),
         logrevolbal = log(1+revolbal))
```

Create ratio for openacc/totalacc

```{R}
loans = loans %>%
  mutate(ratioacc = openacc/totalacc)
```


Recode (1) verification status and (2) purpose into 7 main categories  
Create new variable purpose_mod

```{R}
table(loans$verificationstatus, useNA = "always")
loans$verified = factor(ifelse(loans$verificationstatus == "Not Verified", "N","Y"))
table(loans$verified, loans$verificationstatus)

loans = loans%>%
  mutate(purpose_mod = recode_factor(purpose,"home_improvement" = "living_expenses", 
                                     "educational" = "living_expenses", "home_improvement" = "living_expenses", "house" = "living_expenses"
                                     , "major_purchase" = "luxury", "medical" = "living_expenses", "moving" = "living_expenses",
                                     "renewable_energy" = "business", "small_business" = "business", "vacation" = "luxury", "wedding" = "living_expenses")) 

unique(loans$purpose_mod)
str(loans$purpose_mod)
```

Factorise catagorical variables

```{R}
loans[,c("creditpolicy", "grade", "homeownership", "verificationstatus","targetloanstatus","purpose")] = 
  lapply(loans[,c("creditpolicy", "grade", "homeownership", "verificationstatus","targetloanstatus","purpose")], as.factor)
```

Plot purpose by loan status for modified purpose category

```{R}
loans %>%
  group_by(purpose_mod, targetloanstatus) %>%
  summarise(count_level = n(), percentage = n()/nrow(loans)) %>%
  ggplot(aes(x = purpose_mod, y = percentage, fill = targetloanstatus)) +
  geom_bar(stat = 'identity') +
  labs(title="Purpose", x = "Purpose", y = "Number", fill = "Loan Status")
```

Create business variables for model evaluation in the end. Lending Club states a 5% upfront fee.

```{R}
loans = loans %>%
  mutate(potl_profit = intrate*loanamnt + 0.05*loanamnt,
         loss = case_when(targetloanstatus == 0 ~ 0,
                          targetloanstatus == 1 ~ as.double(loanamnt)*0.95),
         profit = case_when(loss == 0 ~ potl_profit,
                            loss != 0 ~ 0))

loans %>%
  group_by(grade, targetloanstatus) %>%
  summarize(sum = sum(potl_profit)) %>%
  ungroup() %>%
  mutate(perc = sum/sum(sum))
```

Select Features for Modelling

```{R}
loans_df = select(loans, -c("id","homeownership","annualinc","revolbal","verificationstatus","delinq2yrs", "purpose", "profit", "loss", "potl_profit","openacc"))
glimpse(loans_df)

loans_test = select(loans, c("profit","loss","targetloanstatus"))
glimpse(loans_test)
```

Plot correlation of Numerical Variables  
Visualise dataset for modelling

```{R}
corrplot::corrplot(cor(loans_df[, sapply(loans_df, is.numeric)],
                       use="complete.obs"), method = "number", type='lower')

loans_df = select(loans_df, -c("installment","grade","recodegrade"))
```

Write to csv

```{R} 
write.csv(loans_df, "loansformodelling.csv", row.names = F)
write.csv(loans_test, "loansfortest.csv", row.names = F)
```